### ISSUE TITLE
[prod] indexing generates 500 errors from stanford-mods

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/discovery-dispatcher#122]
## Backtrace

```
line 56 of [PROJECT_ROOT]/app/jobs/indexing_job.rb: run_request
line 12 of [PROJECT_ROOT]/app/jobs/indexing_job.rb: block in perform
line 6 of [PROJECT_ROOT]/app/jobs/indexing_job.rb: perform
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48973/faults/30880454)

**Comment by drh-stanford** [comment]
Here's an example stack trace from sw-indexer -- the `sw_full_title` method is broken for ~169 objects:

See https://github.com/sul-dlss/stanford-mods/blob/v2.2.1/lib/stanford-mods/searchworks.rb#L160

```
E, [2016-09-15T11:17:14.778701 #17409] ERROR -- : put {"default"=>{"format"=>:json}, "controller"=>"base_indexer/items", "action"=>"update", "druid"=>"ym741vj6342", "subtarget"=>"SEARCHWORKSPREVIEW"}

#<NoMethodError: undefined method `+' for nil:NilClass>
undefined method `+' for nil:NilClass
["/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/stanford-mods-2.2.1/lib/stanford-mods/searchworks.rb:160:in `sw_full_title'", "/opt/app/harvestdor/sw-indexer/releases/20160913195822/lib/sw_mapper.rb:37:in `mods_to_title_fields'", "/opt/app/harvestdor/sw-indexer/releases/20160913195822/lib/sw_mapper.rb:17:in `convert_to_solr_doc'", "/opt/app/harvestdor/sw-indexer/releases/20160913195822/lib/sw_indexer_engine.rb:25:in `index'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/base_indexer-3.0.0/app/controllers/base_indexer/items_controller.rb:9:in `update'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:51:in `serve'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/honeybadger-2.6.1/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/honeybadger-2.6.1/lib/honeybadger/config.rb:200:in `with_request'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/honeybadger-2.6.1/lib/honeybadger/rack/error_notifier.rb:30:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/honeybadger-2.6.1/lib/honeybadger/rack/user_feedback.rb:28:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/honeybadger-2.6.1/lib/honeybadger/rack/user_informer.rb:18:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'", "/opt/app/harvestdor/sw-indexer/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'", "/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'", "/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'", "/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'", "/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'", "/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"]
I, [2016-09-15T11:17:14.782815 #17409]  INFO -- :   Rendered text template (0.1ms)
I, [2016-09-15T11:17:14.783272 #17409]  INFO -- : Completed 500 Internal Server Error in 322ms (Views: 4.1ms)
[harvestdor@sw-indexing-prod current]$ 
```

**Comment by peetucket** [comment]
The druid referenced above (https://purl.stanford.edu/ym741vj6342.mods) has some bad MODs, it has a blank titleInfo node as well as a valid one.  It is a Revs item and this bad data was probably created by the editstore updater process.  I am looking into why this might have happened.  We could remediate, or just make the indexer more robust.  Pondering.  Revs-Indexer deals with the problem seamlessly, so I am looking into what I do there.

**Comment by peetucket** [comment]
Ok, I think I can make editstore-updater smarter to not leave lingering empty titleInfo nodes around when edits are made, but this doesn't deal with the existing ones.  My revs-indexing-code only sets a single title in a simplistic way, which works.  Searchworks sets multiple title fields, one of which searches through all of the title fields in MODs, and the stanford-mods gem blows up when one of them is empty.  I suggest we make it more robust in stanford-mods (perhaps just ditching the empty value)

**Comment by peetucket** [comment]
Is there an easy way to get a list of all the druids that failed this way?  I just manually fixed the one above (ym741vj6342) to confirm the problem, and now I need another bad example.

**Comment by peetucket** [comment]
Another example: qq983nj4378  (ym741vj6342 has now been fixed as a test)

**Comment by peetucket** [comment]
PR ready: https://github.com/sul-dlss/stanford-mods/pull/91
